import type { FunnelPageKey } from "@/lib/funnel-export/config";

export type FieldType = "text" | "html" | "list" | "image" | "object-list";

export interface FieldDef {
  path: string;
  type: FieldType;
  label: string;
}

/** Editable content paths per page — editor only touches registered fields. */
export const FIELD_REGISTRY: Record<FunnelPageKey, FieldDef[]> = {
  eventLanding: [
    { path: "heroHeadline", type: "text", label: "Hero headline" },
    { path: "heroSubheadline", type: "text", label: "Hero subheadline" },
    { path: "heroPriceLabel", type: "text", label: "Hero price label" },
    { path: "heroPriceValue", type: "text", label: "Hero price value" },
    { path: "ctaText", type: "text", label: "CTA text" },
    { path: "heroMetaLine", type: "text", label: "Hero meta line" },
    { path: "heroHostName", type: "text", label: "Host name" },
    { path: "heroHostTitle", type: "text", label: "Host title" },
    { path: "heroEventDate", type: "text", label: "Event date" },
    { path: "heroEventTime", type: "text", label: "Event time" },
    { path: "heroEventTimezone", type: "text", label: "Event timezone" },
    { path: "videoSectionHeading", type: "text", label: "Video heading" },
    { path: "videoCaption", type: "text", label: "Video caption" },
    { path: "asSeenOnEyebrow", type: "text", label: "As featured in eyebrow" },
    { path: "pressLogos", type: "object-list", label: "Press logos" },
    { path: "audienceHeading", type: "text", label: "Audience heading" },
    { path: "audienceItems", type: "list", label: "Audience items" },
    { path: "vpHeading", type: "text", label: "Value prop heading" },
    { path: "outcomesHeading", type: "text", label: "Outcomes heading" },
    { path: "faqItems", type: "object-list", label: "FAQ items" },
    { path: "finalCtaLine", type: "text", label: "Final CTA line" },
    { path: "finalCtaText", type: "text", label: "Final CTA text" },
    { path: "ftcDisclaimer", type: "text", label: "FTC disclaimer" },
    { path: "heroBackgroundImageUrl", type: "image", label: "Hero background" },
  ],
  eventCheckout: [
    { path: "priceRangeCopy", type: "text", label: "Price range copy" },
    { path: "benefits", type: "list", label: "Sidebar benefits" },
    { path: "ctaText", type: "text", label: "Submit button text" },
    { path: "guaranteeText", type: "text", label: "Submit guarantee" },
    { path: "ftcDisclaimer", type: "text", label: "FTC disclaimer" },
    { path: "checkoutSidebarImageUrl", type: "image", label: "Sidebar image" },
  ],
  upsell: [
    { path: "confirmationBannerText", type: "text", label: "Confirmation banner" },
    { path: "eyebrow", type: "text", label: "Eyebrow" },
    { path: "headline", type: "text", label: "Headline / tagline" },
    { path: "description", type: "text", label: "Description" },
    { path: "includedTitle", type: "text", label: "Included section title" },
    { path: "includedItems", type: "object-list", label: "Included items" },
    { path: "testimonialQuotes", type: "object-list", label: "Testimonial quotes" },
    { path: "savingAmount", type: "text", label: "Saving amount" },
    { path: "urgencyNote", type: "html", label: "Urgency note" },
    { path: "yesCtaText", type: "text", label: "Yes CTA" },
    { path: "yesCtaSubText", type: "text", label: "Yes CTA subtext" },
    { path: "declineText", type: "text", label: "Decline text" },
    { path: "productImageUrl", type: "image", label: "Product image" },
  ],
  eventThankYou: [
    { path: "label", type: "text", label: "Confirmation label" },
    { path: "headline", type: "text", label: "Headline" },
    { path: "subheadline", type: "text", label: "Subheadline" },
    { path: "emailNote", type: "text", label: "Email note" },
    { path: "nextStepsHeading", type: "text", label: "Next steps heading" },
    { path: "nextSteps", type: "object-list", label: "Next steps" },
    { path: "calendarHeading", type: "text", label: "Calendar heading" },
    { path: "calendarSub", type: "text", label: "Calendar subtext" },
    { path: "zoomNote", type: "text", label: "Zoom note" },
    { path: "shareHeading", type: "text", label: "Share heading" },
    { path: "shareSub", type: "text", label: "Share subtext" },
    { path: "personalNoteHeadline", type: "text", label: "Personal note headline" },
    { path: "personalNoteParagraphs", type: "list", label: "Personal note paragraphs" },
    { path: "personalNoteSignature", type: "text", label: "Personal note signature" },
    { path: "backgroundImageUrl", type: "image", label: "Hero background" },
  ],
  replay: [
    { path: "offerBarLabel", type: "text", label: "Offer bar label" },
    { path: "offerBarTitle", type: "text", label: "Offer bar title" },
    { path: "offerBarUrgency", type: "text", label: "Offer bar urgency" },
    { path: "offerBarPrice", type: "text", label: "Offer bar price" },
    { path: "eyebrow", type: "text", label: "Eyebrow" },
    { path: "headline", type: "text", label: "Headline" },
    { path: "subtitle", type: "text", label: "Subheadline" },
    { path: "metaRecordings", type: "text", label: "Meta — recordings" },
    { path: "metaAccess", type: "text", label: "Meta — access" },
    { path: "resourcesLabel", type: "text", label: "Resources label" },
    { path: "videos", type: "object-list", label: "Video parts" },
    { path: "commentsEyebrow", type: "text", label: "Comments eyebrow" },
    { path: "commentsTitle", type: "text", label: "Comments title" },
    { path: "comments", type: "object-list", label: "Live comments" },
    { path: "programCtaLabel", type: "text", label: "Program CTA label" },
    { path: "programCtaHeadline", type: "text", label: "Program CTA headline" },
    { path: "programCtaDescription", type: "text", label: "Program CTA description" },
    { path: "programCtaBenefits", type: "list", label: "Program CTA benefits" },
    { path: "programCtaPrice", type: "text", label: "Program CTA price" },
    { path: "programCtaPlanText", type: "text", label: "Program CTA plan text" },
    { path: "programCtaUrgency", type: "text", label: "Program CTA urgency" },
    { path: "programCtaEnrolText", type: "text", label: "Enrol button text" },
    { path: "ftcHeading", type: "text", label: "Disclaimer heading" },
    { path: "ftcText", type: "text", label: "Disclaimer body" },
    { path: "heroBackgroundImageUrl", type: "image", label: "Header background" },
  ],
  programmeLanding: [
    // Hero
    { path: "heroEyebrow", type: "text", label: "Hero eyebrow" },
    { path: "heroHeadline", type: "text", label: "Hero headline" },
    { path: "heroSubheadline", type: "text", label: "Hero subheadline" },
    { path: "heroMeta", type: "list", label: "Hero meta items" },
    { path: "heroCtaText", type: "text", label: "Hero CTA text" },
    { path: "heroUrgency", type: "text", label: "Hero urgency" },
    // Vision
    { path: "visionEyebrow", type: "text", label: "Vision eyebrow" },
    { path: "visionHeading", type: "text", label: "Vision heading" },
    { path: "visionItems", type: "list", label: "Vision items" },
    { path: "visionCtaText", type: "text", label: "Vision CTA text" },
    { path: "visionCtaNote", type: "text", label: "Vision CTA note" },
    // Already tried
    { path: "alreadyTriedEyebrow", type: "text", label: "Already tried eyebrow" },
    { path: "alreadyTriedHeading", type: "text", label: "Already tried heading" },
    { path: "alreadyTriedBody", type: "list", label: "Already tried body" },
    { path: "alreadyTriedTags", type: "list", label: "Already tried tags" },
    // Promise
    { path: "promiseHeading", type: "text", label: "Promise heading" },
    { path: "promiseBody", type: "list", label: "Promise body" },
    { path: "promiseBullets", type: "list", label: "Promise bullets" },
    // Includes
    { path: "includesEyebrow", type: "text", label: "Includes eyebrow" },
    { path: "includesHeading", type: "text", label: "Includes heading" },
    { path: "includesItems", type: "object-list", label: "Includes items" },
    // Sessions
    { path: "sessionEyebrow", type: "text", label: "Session eyebrow" },
    { path: "sessionHeading", type: "text", label: "Session heading" },
    { path: "sessionWeeks", type: "object-list", label: "Session weeks" },
    // Video testimonials
    { path: "videoTestimonialsEyebrow", type: "text", label: "Video testimonials eyebrow" },
    { path: "videoTestimonialsHeading", type: "text", label: "Video testimonials heading" },
    // Credibility
    { path: "credibilityQuote", type: "text", label: "Credibility quote" },
    { path: "credibilityAttribution", type: "text", label: "Credibility attribution" },
    // Bonuses
    { path: "bonusesEyebrow", type: "text", label: "Bonuses eyebrow" },
    { path: "bonusesHeading", type: "text", label: "Bonuses heading" },
    { path: "bonusesItems", type: "object-list", label: "Bonus items" },
    { path: "bonusesTotal", type: "text", label: "Bonuses total" },
    // Mid price
    { path: "midPriceLabel", type: "text", label: "Mid price label" },
    { path: "midPriceCtaText", type: "text", label: "Mid price CTA" },
    { path: "midPriceUrgency", type: "text", label: "Mid price urgency" },
    // Outcomes
    { path: "outcomesEyebrow", type: "text", label: "Outcomes eyebrow" },
    { path: "outcomesHeading", type: "text", label: "Outcomes heading" },
    { path: "outcomesBody", type: "text", label: "Outcomes body" },
    { path: "outcomesItems", type: "object-list", label: "Outcome items" },
    { path: "outcomesCtaText", type: "text", label: "Outcomes CTA text" },
    // Testimonials section
    { path: "testimonialsEyebrow", type: "text", label: "Testimonials eyebrow" },
    { path: "testimonialsHeading", type: "text", label: "Testimonials heading" },
    // Pricing
    { path: "pricingEyebrow", type: "text", label: "Pricing eyebrow" },
    { path: "pricingHeading", type: "text", label: "Pricing heading" },
    { path: "pricingSubheading", type: "text", label: "Pricing subheading" },
    { path: "pricingCtaText", type: "text", label: "Pricing CTA text" },
    { path: "pricingUrgency", type: "text", label: "Pricing urgency" },
    // Host bio
    { path: "bioEyebrow", type: "text", label: "Bio eyebrow" },
    { path: "bioName", type: "text", label: "Host name" },
    { path: "bioParagraphs", type: "list", label: "Bio paragraphs" },
    { path: "bioCredentials", type: "list", label: "Bio credentials" },
    // FAQ
    { path: "faqEyebrow", type: "text", label: "FAQ eyebrow" },
    { path: "faqItems", type: "object-list", label: "FAQ items" },
    // Final CTA
    { path: "finalCtaHeadline", type: "text", label: "Final CTA headline" },
    { path: "finalCtaBody", type: "text", label: "Final CTA body" },
    { path: "finalCtaText", type: "text", label: "Final CTA button" },
    { path: "finalCtaDeadline", type: "text", label: "Final CTA deadline" },
    { path: "ftcDisclaimer", type: "text", label: "FTC disclaimer" },
    // Images
    { path: "heroBackgroundImageUrl", type: "image", label: "Hero background" },
    { path: "programmeFeatureImageUrl", type: "image", label: "Feature image" },
    { path: "finalCtaBackgroundUrl", type: "image", label: "Final CTA background" },
  ],
  programmeCheckout: [
    { path: "programEyebrow", type: "text", label: "Program eyebrow" },
    { path: "benefits", type: "list", label: "Order benefits" },
    { path: "guaranteeTitle", type: "text", label: "Guarantee title" },
    { path: "guaranteeText", type: "text", label: "Guarantee text" },
    { path: "ctaText", type: "text", label: "Submit button text" },
    { path: "ftcDisclaimer", type: "text", label: "FTC disclaimer" },
    { path: "programmeImageUrl", type: "image", label: "Programme image" },
  ],
  programmeThankYou: [
    { path: "label", type: "text", label: "Confirmation label" },
    { path: "headline", type: "text", label: "Headline" },
    { path: "subheadline", type: "text", label: "Subheadline" },
    { path: "welcomeMessage", type: "text", label: "Welcome message" },
    { path: "emailNote", type: "html", label: "Email note" },
    { path: "nextHeadline", type: "text", label: "Next steps headline" },
    { path: "steps", type: "object-list", label: "Next steps" },
    { path: "scheduleIntro", type: "text", label: "Schedule intro" },
    { path: "noteParagraphs", type: "list", label: "Personal note paragraphs" },
    { path: "commitmentHeadline", type: "text", label: "Commitment headline" },
    { path: "commitmentItems", type: "list", label: "Commitment items" },
    { path: "accessCardTitle", type: "text", label: "Access card title" },
    { path: "backgroundImageUrl", type: "image", label: "Hero background" },
  ],
};
